//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Administracion.Servicio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioTerminalSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioTerminal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarCompaniaActivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarDestinoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDestinoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarDestinoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarDestinoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDestinosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEstadisticasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSinPartirOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaQueSeVeanOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpleadoActivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioTerminal() {
            this.Url = global::Administracion.Properties.Settings.Default.Administracion_Servicio_ServicioTerminal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarCompaniaCompletedEventHandler AgregarCompaniaCompleted;
        
        /// <remarks/>
        public event EliminarCompaniaCompletedEventHandler EliminarCompaniaCompleted;
        
        /// <remarks/>
        public event ModificarCompaniaCompletedEventHandler ModificarCompaniaCompleted;
        
        /// <remarks/>
        public event BuscarCompaniaActivaCompletedEventHandler BuscarCompaniaActivaCompleted;
        
        /// <remarks/>
        public event ListarCompaniasCompletedEventHandler ListarCompaniasCompleted;
        
        /// <remarks/>
        public event AgregarDestinoCompletedEventHandler AgregarDestinoCompleted;
        
        /// <remarks/>
        public event EliminarDestinoCompletedEventHandler EliminarDestinoCompleted;
        
        /// <remarks/>
        public event ModificarDestinoCompletedEventHandler ModificarDestinoCompleted;
        
        /// <remarks/>
        public event BuscarDestinoCompletedEventHandler BuscarDestinoCompleted;
        
        /// <remarks/>
        public event ListarDestinosCompletedEventHandler ListarDestinosCompleted;
        
        /// <remarks/>
        public event ListarEstadisticasCompletedEventHandler ListarEstadisticasCompleted;
        
        /// <remarks/>
        public event AgregarViajeCompletedEventHandler AgregarViajeCompleted;
        
        /// <remarks/>
        public event EliminarViajeCompletedEventHandler EliminarViajeCompleted;
        
        /// <remarks/>
        public event ModificarViajeCompletedEventHandler ModificarViajeCompleted;
        
        /// <remarks/>
        public event ListarCompletedEventHandler ListarCompleted;
        
        /// <remarks/>
        public event ListarSinPartirCompletedEventHandler ListarSinPartirCompleted;
        
        /// <remarks/>
        public event BuscarViajeCompletedEventHandler BuscarViajeCompleted;
        
        /// <remarks/>
        public event ParaQueSeVeanCompletedEventHandler ParaQueSeVeanCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event AgregarEmpleadoCompletedEventHandler AgregarEmpleadoCompleted;
        
        /// <remarks/>
        public event EliminarEmpleadoCompletedEventHandler EliminarEmpleadoCompleted;
        
        /// <remarks/>
        public event ModificarEmpleadoCompletedEventHandler ModificarEmpleadoCompleted;
        
        /// <remarks/>
        public event BuscarEmpleadoActivoCompletedEventHandler BuscarEmpleadoActivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarCompania(Compania C) {
            this.Invoke("AgregarCompania", new object[] {
                        C});
        }
        
        /// <remarks/>
        public void AgregarCompaniaAsync(Compania C) {
            this.AgregarCompaniaAsync(C, null);
        }
        
        /// <remarks/>
        public void AgregarCompaniaAsync(Compania C, object userState) {
            if ((this.AgregarCompaniaOperationCompleted == null)) {
                this.AgregarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCompaniaOperationCompleted);
            }
            this.InvokeAsync("AgregarCompania", new object[] {
                        C}, this.AgregarCompaniaOperationCompleted, userState);
        }
        
        private void OnAgregarCompaniaOperationCompleted(object arg) {
            if ((this.AgregarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarCompania(Compania C) {
            this.Invoke("EliminarCompania", new object[] {
                        C});
        }
        
        /// <remarks/>
        public void EliminarCompaniaAsync(Compania C) {
            this.EliminarCompaniaAsync(C, null);
        }
        
        /// <remarks/>
        public void EliminarCompaniaAsync(Compania C, object userState) {
            if ((this.EliminarCompaniaOperationCompleted == null)) {
                this.EliminarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCompaniaOperationCompleted);
            }
            this.InvokeAsync("EliminarCompania", new object[] {
                        C}, this.EliminarCompaniaOperationCompleted, userState);
        }
        
        private void OnEliminarCompaniaOperationCompleted(object arg) {
            if ((this.EliminarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarCompania(Compania C) {
            this.Invoke("ModificarCompania", new object[] {
                        C});
        }
        
        /// <remarks/>
        public void ModificarCompaniaAsync(Compania C) {
            this.ModificarCompaniaAsync(C, null);
        }
        
        /// <remarks/>
        public void ModificarCompaniaAsync(Compania C, object userState) {
            if ((this.ModificarCompaniaOperationCompleted == null)) {
                this.ModificarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCompaniaOperationCompleted);
            }
            this.InvokeAsync("ModificarCompania", new object[] {
                        C}, this.ModificarCompaniaOperationCompleted, userState);
        }
        
        private void OnModificarCompaniaOperationCompleted(object arg) {
            if ((this.ModificarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCompaniaActiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Compania BuscarCompaniaActiva(string pNombre) {
            object[] results = this.Invoke("BuscarCompaniaActiva", new object[] {
                        pNombre});
            return ((Compania)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCompaniaActivaAsync(string pNombre) {
            this.BuscarCompaniaActivaAsync(pNombre, null);
        }
        
        /// <remarks/>
        public void BuscarCompaniaActivaAsync(string pNombre, object userState) {
            if ((this.BuscarCompaniaActivaOperationCompleted == null)) {
                this.BuscarCompaniaActivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCompaniaActivaOperationCompleted);
            }
            this.InvokeAsync("BuscarCompaniaActiva", new object[] {
                        pNombre}, this.BuscarCompaniaActivaOperationCompleted, userState);
        }
        
        private void OnBuscarCompaniaActivaOperationCompleted(object arg) {
            if ((this.BuscarCompaniaActivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCompaniaActivaCompleted(this, new BuscarCompaniaActivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCompanias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Compania[] ListarCompanias() {
            object[] results = this.Invoke("ListarCompanias", new object[0]);
            return ((Compania[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCompaniasAsync() {
            this.ListarCompaniasAsync(null);
        }
        
        /// <remarks/>
        public void ListarCompaniasAsync(object userState) {
            if ((this.ListarCompaniasOperationCompleted == null)) {
                this.ListarCompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCompaniasOperationCompleted);
            }
            this.InvokeAsync("ListarCompanias", new object[0], this.ListarCompaniasOperationCompleted, userState);
        }
        
        private void OnListarCompaniasOperationCompleted(object arg) {
            if ((this.ListarCompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompaniasCompleted(this, new ListarCompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarDestino", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarDestino(Destino D) {
            this.Invoke("AgregarDestino", new object[] {
                        D});
        }
        
        /// <remarks/>
        public void AgregarDestinoAsync(Destino D) {
            this.AgregarDestinoAsync(D, null);
        }
        
        /// <remarks/>
        public void AgregarDestinoAsync(Destino D, object userState) {
            if ((this.AgregarDestinoOperationCompleted == null)) {
                this.AgregarDestinoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarDestinoOperationCompleted);
            }
            this.InvokeAsync("AgregarDestino", new object[] {
                        D}, this.AgregarDestinoOperationCompleted, userState);
        }
        
        private void OnAgregarDestinoOperationCompleted(object arg) {
            if ((this.AgregarDestinoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarDestinoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarDestino", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarDestino(Destino D) {
            this.Invoke("EliminarDestino", new object[] {
                        D});
        }
        
        /// <remarks/>
        public void EliminarDestinoAsync(Destino D) {
            this.EliminarDestinoAsync(D, null);
        }
        
        /// <remarks/>
        public void EliminarDestinoAsync(Destino D, object userState) {
            if ((this.EliminarDestinoOperationCompleted == null)) {
                this.EliminarDestinoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDestinoOperationCompleted);
            }
            this.InvokeAsync("EliminarDestino", new object[] {
                        D}, this.EliminarDestinoOperationCompleted, userState);
        }
        
        private void OnEliminarDestinoOperationCompleted(object arg) {
            if ((this.EliminarDestinoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDestinoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarDestino", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarDestino(Destino D) {
            this.Invoke("ModificarDestino", new object[] {
                        D});
        }
        
        /// <remarks/>
        public void ModificarDestinoAsync(Destino D) {
            this.ModificarDestinoAsync(D, null);
        }
        
        /// <remarks/>
        public void ModificarDestinoAsync(Destino D, object userState) {
            if ((this.ModificarDestinoOperationCompleted == null)) {
                this.ModificarDestinoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarDestinoOperationCompleted);
            }
            this.InvokeAsync("ModificarDestino", new object[] {
                        D}, this.ModificarDestinoOperationCompleted, userState);
        }
        
        private void OnModificarDestinoOperationCompleted(object arg) {
            if ((this.ModificarDestinoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarDestinoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarDestino", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Destino BuscarDestino(string pCod) {
            object[] results = this.Invoke("BuscarDestino", new object[] {
                        pCod});
            return ((Destino)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarDestinoAsync(string pCod) {
            this.BuscarDestinoAsync(pCod, null);
        }
        
        /// <remarks/>
        public void BuscarDestinoAsync(string pCod, object userState) {
            if ((this.BuscarDestinoOperationCompleted == null)) {
                this.BuscarDestinoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarDestinoOperationCompleted);
            }
            this.InvokeAsync("BuscarDestino", new object[] {
                        pCod}, this.BuscarDestinoOperationCompleted, userState);
        }
        
        private void OnBuscarDestinoOperationCompleted(object arg) {
            if ((this.BuscarDestinoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarDestinoCompleted(this, new BuscarDestinoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDestinos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Destino[] ListarDestinos() {
            object[] results = this.Invoke("ListarDestinos", new object[0]);
            return ((Destino[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDestinosAsync() {
            this.ListarDestinosAsync(null);
        }
        
        /// <remarks/>
        public void ListarDestinosAsync(object userState) {
            if ((this.ListarDestinosOperationCompleted == null)) {
                this.ListarDestinosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDestinosOperationCompleted);
            }
            this.InvokeAsync("ListarDestinos", new object[0], this.ListarDestinosOperationCompleted, userState);
        }
        
        private void OnListarDestinosOperationCompleted(object arg) {
            if ((this.ListarDestinosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDestinosCompleted(this, new ListarDestinosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarEstadisticas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListarEstadisticas() {
            object[] results = this.Invoke("ListarEstadisticas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarEstadisticasAsync() {
            this.ListarEstadisticasAsync(null);
        }
        
        /// <remarks/>
        public void ListarEstadisticasAsync(object userState) {
            if ((this.ListarEstadisticasOperationCompleted == null)) {
                this.ListarEstadisticasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEstadisticasOperationCompleted);
            }
            this.InvokeAsync("ListarEstadisticas", new object[0], this.ListarEstadisticasOperationCompleted, userState);
        }
        
        private void OnListarEstadisticasOperationCompleted(object arg) {
            if ((this.ListarEstadisticasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEstadisticasCompleted(this, new ListarEstadisticasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarViaje(Viaje V) {
            this.Invoke("AgregarViaje", new object[] {
                        V});
        }
        
        /// <remarks/>
        public void AgregarViajeAsync(Viaje V) {
            this.AgregarViajeAsync(V, null);
        }
        
        /// <remarks/>
        public void AgregarViajeAsync(Viaje V, object userState) {
            if ((this.AgregarViajeOperationCompleted == null)) {
                this.AgregarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarViajeOperationCompleted);
            }
            this.InvokeAsync("AgregarViaje", new object[] {
                        V}, this.AgregarViajeOperationCompleted, userState);
        }
        
        private void OnAgregarViajeOperationCompleted(object arg) {
            if ((this.AgregarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarViaje(Viaje V) {
            this.Invoke("EliminarViaje", new object[] {
                        V});
        }
        
        /// <remarks/>
        public void EliminarViajeAsync(Viaje V) {
            this.EliminarViajeAsync(V, null);
        }
        
        /// <remarks/>
        public void EliminarViajeAsync(Viaje V, object userState) {
            if ((this.EliminarViajeOperationCompleted == null)) {
                this.EliminarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarViajeOperationCompleted);
            }
            this.InvokeAsync("EliminarViaje", new object[] {
                        V}, this.EliminarViajeOperationCompleted, userState);
        }
        
        private void OnEliminarViajeOperationCompleted(object arg) {
            if ((this.EliminarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarViaje(Viaje V) {
            this.Invoke("ModificarViaje", new object[] {
                        V});
        }
        
        /// <remarks/>
        public void ModificarViajeAsync(Viaje V) {
            this.ModificarViajeAsync(V, null);
        }
        
        /// <remarks/>
        public void ModificarViajeAsync(Viaje V, object userState) {
            if ((this.ModificarViajeOperationCompleted == null)) {
                this.ModificarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarViajeOperationCompleted);
            }
            this.InvokeAsync("ModificarViaje", new object[] {
                        V}, this.ModificarViajeOperationCompleted, userState);
        }
        
        private void OnModificarViajeOperationCompleted(object arg) {
            if ((this.ModificarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viaje[] Listar() {
            object[] results = this.Invoke("Listar", new object[0]);
            return ((Viaje[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAsync() {
            this.ListarAsync(null);
        }
        
        /// <remarks/>
        public void ListarAsync(object userState) {
            if ((this.ListarOperationCompleted == null)) {
                this.ListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarOperationCompleted);
            }
            this.InvokeAsync("Listar", new object[0], this.ListarOperationCompleted, userState);
        }
        
        private void OnListarOperationCompleted(object arg) {
            if ((this.ListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompleted(this, new ListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSinPartir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viaje[] ListarSinPartir() {
            object[] results = this.Invoke("ListarSinPartir", new object[0]);
            return ((Viaje[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSinPartirAsync() {
            this.ListarSinPartirAsync(null);
        }
        
        /// <remarks/>
        public void ListarSinPartirAsync(object userState) {
            if ((this.ListarSinPartirOperationCompleted == null)) {
                this.ListarSinPartirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSinPartirOperationCompleted);
            }
            this.InvokeAsync("ListarSinPartir", new object[0], this.ListarSinPartirOperationCompleted, userState);
        }
        
        private void OnListarSinPartirOperationCompleted(object arg) {
            if ((this.ListarSinPartirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSinPartirCompleted(this, new ListarSinPartirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viaje BuscarViaje(int pNumero) {
            object[] results = this.Invoke("BuscarViaje", new object[] {
                        pNumero});
            return ((Viaje)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarViajeAsync(int pNumero) {
            this.BuscarViajeAsync(pNumero, null);
        }
        
        /// <remarks/>
        public void BuscarViajeAsync(int pNumero, object userState) {
            if ((this.BuscarViajeOperationCompleted == null)) {
                this.BuscarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarViajeOperationCompleted);
            }
            this.InvokeAsync("BuscarViaje", new object[] {
                        pNumero}, this.BuscarViajeOperationCompleted, userState);
        }
        
        private void OnBuscarViajeOperationCompleted(object arg) {
            if ((this.BuscarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarViajeCompleted(this, new BuscarViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaQueSeVean", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ParaQueSeVean(ViajeInternacional vi, ViajeNacional vn) {
            this.Invoke("ParaQueSeVean", new object[] {
                        vi,
                        vn});
        }
        
        /// <remarks/>
        public void ParaQueSeVeanAsync(ViajeInternacional vi, ViajeNacional vn) {
            this.ParaQueSeVeanAsync(vi, vn, null);
        }
        
        /// <remarks/>
        public void ParaQueSeVeanAsync(ViajeInternacional vi, ViajeNacional vn, object userState) {
            if ((this.ParaQueSeVeanOperationCompleted == null)) {
                this.ParaQueSeVeanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaQueSeVeanOperationCompleted);
            }
            this.InvokeAsync("ParaQueSeVean", new object[] {
                        vi,
                        vn}, this.ParaQueSeVeanOperationCompleted, userState);
        }
        
        private void OnParaQueSeVeanOperationCompleted(object arg) {
            if ((this.ParaQueSeVeanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaQueSeVeanCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado Login(string pCi, string pPass) {
            object[] results = this.Invoke("Login", new object[] {
                        pCi,
                        pPass});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string pCi, string pPass) {
            this.LoginAsync(pCi, pPass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string pCi, string pPass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        pCi,
                        pPass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarEmpleado(Empleado E) {
            this.Invoke("AgregarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void AgregarEmpleadoAsync(Empleado E) {
            this.AgregarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void AgregarEmpleadoAsync(Empleado E, object userState) {
            if ((this.AgregarEmpleadoOperationCompleted == null)) {
                this.AgregarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("AgregarEmpleado", new object[] {
                        E}, this.AgregarEmpleadoOperationCompleted, userState);
        }
        
        private void OnAgregarEmpleadoOperationCompleted(object arg) {
            if ((this.AgregarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarEmpleado(Empleado E) {
            this.Invoke("EliminarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado E) {
            this.EliminarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado E, object userState) {
            if ((this.EliminarEmpleadoOperationCompleted == null)) {
                this.EliminarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("EliminarEmpleado", new object[] {
                        E}, this.EliminarEmpleadoOperationCompleted, userState);
        }
        
        private void OnEliminarEmpleadoOperationCompleted(object arg) {
            if ((this.EliminarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarEmpleado(Empleado E) {
            this.Invoke("ModificarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado E) {
            this.ModificarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado E, object userState) {
            if ((this.ModificarEmpleadoOperationCompleted == null)) {
                this.ModificarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("ModificarEmpleado", new object[] {
                        E}, this.ModificarEmpleadoOperationCompleted, userState);
        }
        
        private void OnModificarEmpleadoOperationCompleted(object arg) {
            if ((this.ModificarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmpleadoActivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado BuscarEmpleadoActivo(string pCi) {
            object[] results = this.Invoke("BuscarEmpleadoActivo", new object[] {
                        pCi});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpleadoActivoAsync(string pCi) {
            this.BuscarEmpleadoActivoAsync(pCi, null);
        }
        
        /// <remarks/>
        public void BuscarEmpleadoActivoAsync(string pCi, object userState) {
            if ((this.BuscarEmpleadoActivoOperationCompleted == null)) {
                this.BuscarEmpleadoActivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpleadoActivoOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpleadoActivo", new object[] {
                        pCi}, this.BuscarEmpleadoActivoOperationCompleted, userState);
        }
        
        private void OnBuscarEmpleadoActivoOperationCompleted(object arg) {
            if ((this.BuscarEmpleadoActivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpleadoActivoCompleted(this, new BuscarEmpleadoActivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Compania {
        
        private string direccionField;
        
        private string nombreField;
        
        private int telefonoField;
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado {
        
        private string ciField;
        
        private string contrasenaField;
        
        private string nombreField;
        
        /// <remarks/>
        public string Ci {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <remarks/>
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ViajeNacional))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ViajeInternacional))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Viaje {
        
        private int numeroField;
        
        private System.DateTime fechaSalidaField;
        
        private System.DateTime fechaArriboField;
        
        private int cantidadAsientosField;
        
        private Empleado usuarioField;
        
        private Destino destinoField;
        
        private Compania companiaField;
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaSalida {
            get {
                return this.fechaSalidaField;
            }
            set {
                this.fechaSalidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaArribo {
            get {
                return this.fechaArriboField;
            }
            set {
                this.fechaArriboField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadAsientos {
            get {
                return this.cantidadAsientosField;
            }
            set {
                this.cantidadAsientosField = value;
            }
        }
        
        /// <remarks/>
        public Empleado Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public Destino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        public Compania Compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Destino {
        
        private string ciudadField;
        
        private string paisField;
        
        private string codField;
        
        private Facilidades[] lasFacilidadesField;
        
        /// <remarks/>
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Cod {
            get {
                return this.codField;
            }
            set {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        public Facilidades[] LasFacilidades {
            get {
                return this.lasFacilidadesField;
            }
            set {
                this.lasFacilidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Facilidades {
        
        private string facilidadField;
        
        /// <remarks/>
        public string Facilidad {
            get {
                return this.facilidadField;
            }
            set {
                this.facilidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ViajeNacional : Viaje {
        
        private int paradasField;
        
        /// <remarks/>
        public int Paradas {
            get {
                return this.paradasField;
            }
            set {
                this.paradasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ViajeInternacional : Viaje {
        
        private bool servicioABordoField;
        
        private string documentosField;
        
        /// <remarks/>
        public bool ServicioABordo {
            get {
                return this.servicioABordoField;
            }
            set {
                this.servicioABordoField = value;
            }
        }
        
        /// <remarks/>
        public string Documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AgregarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void EliminarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ModificarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BuscarCompaniaActivaCompletedEventHandler(object sender, BuscarCompaniaActivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCompaniaActivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCompaniaActivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compania Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compania)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarCompaniasCompletedEventHandler(object sender, ListarCompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compania[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compania[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AgregarDestinoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void EliminarDestinoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ModificarDestinoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BuscarDestinoCompletedEventHandler(object sender, BuscarDestinoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarDestinoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarDestinoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Destino Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Destino)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarDestinosCompletedEventHandler(object sender, ListarDestinosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDestinosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDestinosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Destino[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Destino[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarEstadisticasCompletedEventHandler(object sender, ListarEstadisticasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEstadisticasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEstadisticasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AgregarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void EliminarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ModificarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarCompletedEventHandler(object sender, ListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viaje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viaje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarSinPartirCompletedEventHandler(object sender, ListarSinPartirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSinPartirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSinPartirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viaje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viaje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BuscarViajeCompletedEventHandler(object sender, BuscarViajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viaje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viaje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ParaQueSeVeanCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AgregarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void EliminarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ModificarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BuscarEmpleadoActivoCompletedEventHandler(object sender, BuscarEmpleadoActivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpleadoActivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpleadoActivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591